# Generated by Django 2.1 on 2018-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.BigIntegerField(db_column='call_id', primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField(blank=True, db_column='time_start', null=True)),
                ('time_end', models.DateTimeField(blank=True, db_column='time_end', null=True)),
                ('source', models.CharField(blank=True, db_column='source', max_length=50, null=True)),
                ('destination', models.CharField(blank=True, db_column='destination', max_length=50, null=True)),
            ],
            options={
                'db_table': 'call',
                'managed': True,
            },
        ),
    ]
