# Generated by Django 2.1 on 2018-09-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_cost',
            field=models.FloatField(blank=True, db_column='cost', null=True),
        ),
    ]
