version: '3.2'

services:
  calls_api:
    # image: ptec_challenge
    build:
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: calls_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
      DJANGO_SECRET_KEY: 8m^ea$ekd#q+me%+13mv36++c2bq)sg4c2b(*_ta^8!ml8g(h0
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
#    command:
#    - ./entrypoint.sh
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: